services:
  cf_attack_map:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cf_attack_map
    ports:
      - "8083:8083"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - cf_attack_map_network
    env_file:
      - .env
    environment:
      - REDIS_IP=map_redis
      - TZ=America/Sao_Paulo
    restart: always

  redis:
    image: redis:latest
    container_name: map_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cf_attack_map_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always

networks:
  cf_attack_map_network:
    driver: bridge

volumes:
  redis_data:
